### ISSUE TITLE
ensemble

### ISSUE THREAD

**Issue by starrycos** [hulianyuyy/STGAT#1]
In the experiment, I get a performance of  90.7 and 90.2 for joint and bone stream, respectively,  which is inconsistent with your result. Could you solve this problem, please?

**Comment by hulianyuyy** [comment]
[Here](https://github.com/hulianyuyy/STGAT/blob/0a23c1ad6742820c9c4c11425011ef51b563b803/method_choose/data_choose.py#L16), i have fixed the random seed and disabled cudnn. You could get the same results on the same machine across different iterations. But the results may vary upon different machines. This situation vary according to the software and hardware environments. It has not been fixed yet.

**Comment by starrycos** [comment]
Could you please tell me where can I find the article appendix? Thanks!

**Comment by hulianyuyy** [comment]
I have updated the arxiv version by attaching the appendix. You can redownload it one day later.
