### ISSUE TITLE
How to realize "Separate multi-head learning"

### ISSUE THREAD

**Issue by Vincy-Ying** [hulianyuyy/STGAT#12]
Thanks for your project and there are some issues about it. In STGAB, how to realize "Separate multi-head learning" in the code? What are meanings of "Computed spatial-temporal graph" and "seperated_adjacency"?

**Comment by hulianyuyy** [comment]
"Separate multi-head learning" is realized in line 219 in [st2ransformer_dsta.py](https://github.com/hulianyuyy/STGAT/tree/main/model)
/st2ransformer_dsta.py). The computed spatial-temporal graph is the attention map generated in line 216 in [st2ransformer_dsta.py](https://github.com/hulianyuyy/STGAT/tree/main/model).  "seperated_adjacency" is the predefined adjacent graph by node adjacency in line 218 in [st2ransformer_dsta.py](https://github.com/hulianyuyy/STGAT/tree/main/model).

**Comment by sencer4898** [comment]
@hulianyuyy Is the separate multi-head learning similar to the disentangling strategy from MS-G3D? As I understand, both strategies create a different adjacency for each k-hop neighbor. In disentangling, each neighbor in the k-hop neighborhood gets a fixed weight (and weight=0 for non-neighbors). In separate multi-head learning, k-hop neighbors get an adaptive weight, and non-neighbors get an idle weight (e.g., 1).

**Comment by hulianyuyy** [comment]
Thet are similar in some aspects. In disentangling, each neighbor in the k-hop neighborhood gets a fixed weight (and weight=0 for non-neighbors). In separate multi-head learning, incorporated nodes for k-hop neighbors get an adaptive weight, and non-neighbors get an fixed weight (e.g., 0).
