### ISSUE TITLE
 I got accuracy  89.75 % instead of 90.2%

### ISSUE THREAD

**Issue by musrea** [hulianyuyy/STGAT#14]
Dear Authors ,
I  trained your model as my baseline model with default settings, however I got accuracy  89.75 % instead of 90.2% which is lower than yours. Is there any suggestion or settings can help me to get better accuracy?
Here is my  setting 
model_param: {'num_point': 25, 'num_frame': 128, 'num_subset': 8, 'num_person': 2, 'glo_reg_s': True, 'att_s': True, 'glo_reg_t': False, 'att_t': False, 'dropout': 0, 'attentiondrop': 0, 'dropout2d': 0, 'use_spatial_att': True, 'use_temporal_att': False, 'use_pet': False, 'use_pes': False, 'config': [[64, 64, 16, 1], [64, 64, 16, 1], [64, 128, 32, 2], [128, 128, 32, 1], [128, 256, 64, 2], [256, 256, 64, 1], [256, 256, 64, 1], [256, 256, 64, 1]]}

**Comment by hulianyuyy** [comment]
The accuracy varies slightly across different machines due to different software environments and hardware configurations. I can hardly ensure you get the exactly same result as mine, but the result can be around mine.
