### ISSUE TITLE
Not using gpu

### ISSUE THREAD

**Issue by mahshidaj95** [hulianyuyy/STGAT#15]
Hi, I'm using your code, but I wonder if is it possible to not use gpu and run the code on copu?
My NVIDIA version is too old so I can't use cuda gpu.

**Comment by hulianyuyy** [comment]
Currently, this code doesn't support cpu. And i infer that running this code on cpu may be too slow. Running it on a 2080ti GPU costs about one day. It may consume more than a week on a common cpu.

**Comment by mahshidaj95** [comment]
That's right. thank you.

**Comment by mahshidaj95** [comment]
Hello Dear Hulianyuyy,
I want to run an attention model on skeleton dataset similar to your github
code (STGAT) for human action recognition. However, I don't have a GPU, so
I want to run on a CPU server. Do you know what the minimum RAM requirement
I need?

Sincerely, Mahshid Alijabbari

**Comment by hulianyuyy** [comment]
I'm sorry that i haven't run this code on the cpu server. Thus i don't know the minimum RAM requirement. Maybe you can find a repo that supports the cpu server which may better help you.

**Comment by mahshidaj95** [comment]
Thank you for your response. Actually, my thesis is human action
recognition using graph attention network and I try many codes and neural
network models using attention mechanism, but I didn't get appropriate
results. Can you send me a simpler attention model to fit to the NTU
skeleton dataset? I would be so grateful.
