### ISSUE TITLE
Definition of generate skeleton data output

### ISSUE THREAD

**Issue by mahshidaj95** [hulianyuyy/STGAT#17]
Hi,
What are the output of command "python prepare/ntu_60/gendata.py"?
Are the positions of skeleton joints 3d and 2d?

**Comment by hulianyuyy** [comment]
This command "python prepare/ntu_60/gendata.py" generates four output files, i.e., 'train_data_joint.py' and 'val_data_joint.py' for x-sub and x-view settings, respectively.
The skeleton joints are 2d, with an extra confidence dimension along channel.

**Comment by mahshidaj95** [comment]
So, Are the numbers in these four numpy array outputs, coordinates of 2d skeleton joints in the image?

**Comment by hulianyuyy** [comment]
Yes, it's right



---Original---
From: "Mahshid ***@***.***&gt;
Date: Sat, Oct 7, 2023 15:33 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [hulianyuyy/STGAT] Definition of generate skeleton data output(Issue #17)




 
So, Are the numbers in these four numpy array outputs, coordinates of 2d skeleton joints in the image?

**Comment by mahshidaj95** [comment]
Thank you. However, if they are coordinates of 2d skeleton joints in the image, why some numbers in the 'train_data_joint.py' are negative?

**Comment by mahshidaj95** [comment]
> Yes, it's right
> […](#)
> ---Original--- From: "Mahshid ***@***.***&gt; Date: Sat, Oct 7, 2023 15:33 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [hulianyuyy/STGAT] Definition of generate skeleton data output(Issue #17) So, Are the numbers in these four numpy array outputs, coordinates of 2d skeleton joints in the image? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

Thank you. However, if they are coordinates of 2d skeleton joints in the image, why some numbers in the 'train_data_joint.py' are negative?

**Comment by hulianyuyy** [comment]
The coordinates have been normalize into [-1, 1] according to the height and width of images.

**Comment by mahshidaj95** [comment]
> The coordinates have been normalize into [-1, 1] according to the height and width of images.

That's right thank you. Also, are the shape of the 'train_data_.joint.npy' file (number of samples, number of coordinate channels=3, number of frames=300, number of joints=25, number of persons in the frame=2), respectively?

**Comment by hulianyuyy** [comment]
Yes, it's right. Especially, there are totally 3 channels with x, y coordinates and an extra confidence channel.

**Comment by mahshidaj95** [comment]
> Yes, it's right. Especially, there are totally 3 channels with x, y coordinates and an extra confidence channel.

Thank you very much. Additionally, can I ask what is extra confidence channel in image?

**Comment by hulianyuyy** [comment]
It' the confidence logit generated by Openpose when performing pose estimation.



---Original---
From: "Mahshid ***@***.***&gt;
Date: Thu, Oct 12, 2023 23:19 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [hulianyuyy/STGAT] Definition of generate skeleton data output(Issue #17)




  
Yes, it's right. Especially, there are totally 3 channels with x, y coordinates and an extra confidence channel.
  
Thank you very much. Additionally, can I ask what is extra confidence channel in image?
