### ISSUE TITLE
File missing

### ISSUE THREAD

**Issue by ssyh98** [hulianyuyy/STGAT#18]
Hello, may I ask which program was run to obtain the samples file in line 272 of prepare/ntu_60/gendata for the preprocessing of the data set? Perhaps you could update your process of running the program in detail?

**Comment by hulianyuyy** [comment]
You can find the files [here](https://github.com/shahroudy/NTURGB-D#samples-with-missing-skeletons).

**Comment by ssyh98** [comment]
> You can find the files [here](https://github.com/shahroudy/NTURGB-D#samples-with-missing-skeletons).

OK, I find it ,Thank you very much!
