### ISSUE TITLE
Some questions regarding the config file

### ISSUE THREAD

**Issue by sencer4898** [hulianyuyy/STGAT#19]
Dear Lianyu,

Thank you for making the code available. I have some questions related to your code:

1. Is pre_trained_model and last_model have similar functionalities? (Except pre_trained_model is affected from ignore_weights)
2. 2. is ignore_weights['fc'] equivalent to include_top = False? (for training a task-specific last layer)
3. Are the scripts not data flexible (suitable to only NTU and kinetics)? (Because data_choose raises error otherwise)

Thanks in advance

**Comment by hulianyuyy** [comment]
1. They have similar functionalities. In general pre_trained_model is used to load a pretrained weight for training, while the last_model is used to load a checkpoint to continue training.
2. We don't have a hyperparameter named include_top. ignore_weights['fc'] means reinitializing the fc layer for training.
3. Yes.

**Comment by sencer4898** [comment]
Could you include a requirements.txt or a similar file in your repository with the necessary packages and their versions? It would make the reproduction of the results a lot easier.

**Comment by hulianyuyy** [comment]
I have uploaded one.
