### ISSUE TITLE
train.py: error: unrecognized arguments

### ISSUE THREAD

**Issue by mahshidaj95** [hulianyuyy/STGAT#2]
Hi, I want to run training and testing command code, and when I run:
python train_val_test/train.py --config /my_path/config/ntu/ntu60_dsta.yaml

I got this error:
train.py: error: unrecognized arguments: --config /my_path/config/ntu/ntu120_dsta.yaml
  [0.000s] Operation failed

The path of the config file is correct.

 Do you know what is the problem?

**Comment by hulianyuyy** [comment]
Sorry, you may use '-config' instead of '--config', i will modify the readme file
