### ISSUE TITLE
UnicodeDecodeError&TypeError

### ISSUE THREAD

**Issue by ZhaoYu810** [hulianyuyy/STGAT#21]
![111](https://github.com/hulianyuyy/STGAT/assets/84625897/d4110f74-47e5-46f3-aa8e-f3acfad3c64f)
![222](https://github.com/hulianyuyy/STGAT/assets/84625897/5b6d25b6-08f5-46ca-9261-33ee533e4e7b)
      观察到报错信息似乎分为两部分（如图），其中以**“During handling of the above exception, another exception occurred:”**为界。问题1是**“UnicodeDecodeError: 'gbk' codec can't decode byte 0xae in position 129: illegal multibyte sequence”**，问题2是**“TypeError: expected str, bytes or os.PathLike object, not NoneType”**。

**Comment by ZhaoYu810** [comment]
解决方法也不算难，在overflow上发现不可以使用中文，注意下载的文件名默认是“STGAT-main”其中的这个“-”算是中文字符（好细的细节）删改一下就可以了。

**Comment by hulianyuyy** [comment]
Mant thanks for your response!
