### ISSUE TITLE
Configuration Issues

### ISSUE THREAD

**Issue by JinY-Shi** [hulianyuyy/STGAT#25]
Hello,I have some questions in the process of reproducing the code. I hope you can help me answer them.
1. how should the joint_position_in_img.npy file generated after data processing be used? 
2. num_skip_frame=1 means use motion information, num_skip_frame=2 means do not use motion information? If num_skip_frame: is not filled in the config, does it mean that motion information is not used? 
3. In the ensemble.py fusion file, how do spatial_temporal, spatial, temporal_slow, and temporal_fast correspond to bones, joints, and their motion states?

**Comment by hulianyuyy** [comment]
1. Currently, the joint_position_in_img.npy is not used in this repo.
2. num_skip_frame=1 means using motion information, num_skip_frame= null means do not use motion information.
3. spatial_temporal, spatial, temporal_slow, and temporal_fast don't have specific meanings here. You just need to set the bone, joint, joint-motion and bone-motion prediction files for them as inputs. Any order is acceptable.
