### ISSUE TITLE
Memory less error

### ISSUE THREAD

**Issue by mahshidaj95** [hulianyuyy/STGAT#3]
Hi,
I'm using this code, after processing ./work_dir/ntu60/baseline, I got this error:

self = reduction.pickle.load(from_parent)
MemoryError

Does anyone know how to fix it?
Thank you

**Comment by hulianyuyy** [comment]
It seems you've run out of memory on your system. You can reduce memory usage by using a smaller DATALOADER.NUM_WORKERS
