### ISSUE TITLE
how to visualize the egde in the paper? 

### ISSUE THREAD

**Issue by neverstoplearn** [hulianyuyy/STGAT#4]

**Comment by hulianyuyy** [comment]
I have uploaded a 'ntu_visualize_add_attention.py'. You could save the attention weights in each head as a '.npy' file, and then visualize it.

**Comment by xudadi001** [comment]
您好，请问您以下问题如何解决。
![_ %YQVOTN4X1E$4QGKU}ZUR](https://user-images.githubusercontent.com/65487336/201900830-fc2f07bf-0f8a-4992-a801-acc1524d4ffb.png)
![Y A4J5CG7UCH$@(@8P_CC2N](https://user-images.githubusercontent.com/65487336/201900846-0a841a57-8670-4b3e-88a1-cfb0c0942829.png)
请问这两个选择分别是什么意思？
![35B`G3W@UR%@7IX(NF{2S5U](https://user-images.githubusercontent.com/65487336/201900960-845fc486-396c-4a57-853d-232f54d546af.png)
这个问题我在csdn中查到是因为windows系统需要将num_worker修改为0，我在您代码中找到了如下
![H 53K~XBTU8Q9ZTXB`}P 5](https://user-images.githubusercontent.com/65487336/201901582-87906d96-cfe4-41ff-bb8a-bdfec4d06384.png)
请问是修改这个吗？
将其修改为0后我又遇到了如下问题：
![HREA7Z_{J(2UDK13)~H_PWN](https://user-images.githubusercontent.com/65487336/201902231-01fcd223-9dbe-4850-bfc3-58f24d52858e.png)
您能告诉我如何解决这些问题吗？万分感谢

**Comment by xudadi001** [comment]
![image](https://user-images.githubusercontent.com/65487336/201907343-34fd2e9e-3f23-4acf-933c-04eb020a1d57.png)
该问题好像与worker数值没有关系，但是我不只带是为什么

**Comment by hulianyuyy** [comment]
The code will create a new dir if you run. You can choose to delete the files by y/n. The workers denote how many Cpu threads are used. It seems that you don't load the dataset. Please check the dataset path.



---Original---
From: ***@***.***&gt;
Date: Tue, Nov 15, 2022 19:21 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [hulianyuyy/STGAT] how to visualize the egde in the paper? (Issue #4)




 

 该问题好像与worker数值没有关系，但是我不只带是为什么

**Comment by xudadi001** [comment]
![K5FJ@G8AXGTPIQ8@_E@OU}P](https://user-images.githubusercontent.com/65487336/201913386-c4e42193-6853-45bb-b884-cfd9138df431.png)
![ZF(80 3SW8FK0T%Z5(812E1](https://user-images.githubusercontent.com/65487336/201913406-b29689ba-8756-4905-a7c9-eda979ea9fab.png)
您好，这是我目前的设置，请问dataset path指的是什么？

**Comment by hulianyuyy** [comment]
The dataset path refers to the data_path and label_path. I haven't tried this code on Window systems. I speculate that maybe you could set two / in the path. For example, D://STGAT//ST-GAT//STGAT-main//STGAT-main//data//kinetics//val_data.npy. Windows uses two / in the path configuration.

**Comment by xudadi001** [comment]
![IEAYXQ9T7GACWXD5C{@CUVO](https://user-images.githubusercontent.com/65487336/201919090-de75d710-bbd4-4d0d-b1e9-699946399093.png)
wen'ti'yi'jiu问题依旧存在，我刚刚在linux系统尝试过，会报同样的错误。我使用的数据集之前我在ST-GCN上处理并使用的kinetics-skeleton数据集，我直接把他们放在了自己建的data文件夹中。请问和这些有关系吗？

**Comment by hulianyuyy** [comment]
It doesn't matter. I speculate that the data are not correctly loaded but i'm not sure why. Maybe you could try the ntu rgb+d 60 dataset and see if there is any problem. I'll keep on this.

**Comment by xudadi001** [comment]
您好，为什么我下载的60和120数据集，解压后没有samples_with_missing_skeletons.txt这个文件

**Comment by hulianyuyy** [comment]
You may find it in the stgcn repo



---Original---
From: ***@***.***&gt;
Date: Tue, Nov 15, 2022 23:23 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [hulianyuyy/STGAT] how to visualize the egde in the paper? (Issue #4)




 
您好，为什么我下载的60和120数据集，解压后没有samples_with_missing_skeletons.txt这个文件

**Comment by xudadi001** [comment]
您好，我在训练过程中又遇到了一个新问题
![5@B{4HT0UAPX%SS1)AD$}XR](https://user-images.githubusercontent.com/65487336/202332553-77d4951f-bdd3-4745-9429-6acede19dc54.png)
请问这个问题该如何解决

**Comment by hulianyuyy** [comment]
It seems that the global_step is a tuple variable. However, i check the code and global_step should be a int variable. I haven't run into this error.

**Comment by xudadi001** [comment]
请问您有遇到这个问题吗？还请问您使用的python版本是多少？
![5@}DGZM(7FY}W0{H8OE}2FP](https://user-images.githubusercontent.com/65487336/202415644-7ad8277b-5eb8-492b-a0b4-efd74721ae20.png)

**Comment by hulianyuyy** [comment]
I have fixed some errors. I also retest this code on the NTU and Kinetics dataset. You could redownload it for a try.
