### ISSUE TITLE
我该怎么样解决这个问题

### ISSUE THREAD

**Issue by xudadi001** [hulianyuyy/STGAT#6]
![ZYPPXJ {K4BWW$8MC5RRA](https://user-images.githubusercontent.com/65487336/201657203-7cda4eb2-337c-4f16-a66d-02b0ac1a46c3.png)

**Comment by hulianyuyy** [comment]
You can delete this line directly, as this dataset is not used in our paper. I will update it later.



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月14日(周一) 晚上8:13
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [hulianyuyy/STGAT] 我该怎么样解决这个问题 (Issue #6)
