### ISSUE TITLE
十分感谢您在百忙之中抽出时间帮我解答问，让我获益匪浅。还请问您一个问题

### ISSUE THREAD

**Issue by xudadi001** [hulianyuyy/STGAT#7]
![)ZM7)5YV$TYQ1M)STH88@42](https://user-images.githubusercontent.com/65487336/201667666-e5b8899e-5d83-41b9-b063-32259aa1e18d.png)
我使用的是2060单卡。
cuda 11.6

**Comment by hulianyuyy** [comment]
You should set the device id as 0 if you only have one Gpu.



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月14日(周一) 晚上9:07
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [hulianyuyy/STGAT] 十分感谢您在百忙之中抽出时间帮我解答问，让我获益匪浅。还请问您一个问题 (Issue #7)




 

 我使用的是2060单卡。
 cuda 11.6
