### ISSUE TITLE
Regarding ensemble 

### ISSUE THREAD

**Issue by sankamohotttala** [hulianyuyy/STGAT#8]
Hello, Thanks for the openly available code and congratulations on the paper. I trained the model without changing the num_skip_frame and decouple-spatial params and was able to get 88.35% for 30 epochs and steps=[5,25]. Unfortunately I couldn't use the same batch size and # of epochs due to computational costs.
Is this the final STGAT , the one you obtained 90.2% as in table 1 in your paper? if so then the deviation is probably due to the above mentioned reasons I guess.
From the code , it seems decouple_spatial result in bone stream as in 2s-agcn and num_skip_frame result in motion for the stream. so basically by num_skip_frame ={None, 1}, and decouple_spatial ={False,True} we can get all 4 streams.  If so these 4 must be correspond to 4 models used in ensemble.py {spatial_temporal, spatial, temporal_slow,temporal_fast}. Am I correct? if not please let me know.

if so why use num_skip_frame =2 ? is this like dilation=2? how does it fit in the ensmble? I have read your paper only halfway at this point so may be this is already addressed there. if so sorry about asking this. thank you.

**Comment by hulianyuyy** [comment]
Many thanks for your attention
1. The accuracy drops drastically with fewer training epochs.
2. Your understanding about four streams is correct. If using num_skip_frame =2, you could obtain motion (temporal difference) information with adjacent 2 frames. I suspect this may lead to inferior performance compared to num_skip_frame =2 as it dilates the motion information. But i haven't tried it. You could view it as another stream and i suspect you could gain higher accuracy with multiple streams with num_skip_frame <=N with N a larger integer.

**Comment by sankamohotttala** [comment]
Thanks
